version: '3'

volumes:
  postgres_data:
  static_volume:

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - api_yamdb/.env

  web:
    image: liderk/yamdb_final:latest
    restart: always
    command: sh -c "python manage.py migrate && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/yamdb/static
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - api_yamdb/.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/yamdb/static
    ports:
      - 80:80
    depends_on:
      - web